### ISSUE TITLE
can't start client - gui

### ISSUE THREAD

**Issue by satkas** [ikus060/minarca#16]
My client (giu) has stopped working for some time now. In the pseudo terminal it's ok.
**$ minarca status**
Remote server:          127.0.0.1
Connectivity status:    Connected
Last successful backup: Thu, 31 Aug 2023 14:01:17
Last backup date:       Thu, 31 Aug 2023 14:01:17
Last backup status:     SUCCESS

`$ minarca ui
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"`

After clicking on the client icon, I see in the upper left corner of the screen (gnome) that the client shows up, but the window is nowhere to be drawn. My system is Debian 12. Minarca 4.5.4

how can i debug the problem for you?  After clicking on the client icon and viewing the logs, there are no problems
`2023-08-31 14:10:31,215 [6264][DEBUG][MainThread  ] Using selector: EpollSelector
2023-08-31 14:10:36,140 [6264][DEBUG][ThreadPoolEx] Starting new HTTPS connection (1): latest.ikus-soft.com:443
2023-08-31 14:10:36,897 [6264][DEBUG][ThreadPoolEx] https://latest.ikus-soft.com:443 "GET /minarca/latest_version HTTP/1.1" 200 5`

**Comment by satkas** [comment]
I edited the movie
[https://satkas.waw.pl/minarca.webm](url)

**Comment by ikus060** [comment]
Thanks @satkas  for your help. According to the stack trace, the application is running.

It possible the window for Minarca get created, but get hidden. You may try to list the window from x server using: `xwininfo -tree -root` when minarca ui is running. 

Then look for something like this:
```
     0x40f657 (has no name): ()  920x615+3150+490  +3150+490
        1 child:
        0x5a003bf "Minarca Backup": ("minarca" "Minarca")  900x560+10+45  +3160+535
```

**Comment by ikus060** [comment]
So far, the only thing I can think of is the window being created outside the visible space of you desktop. The coordinate `+2526+358` seams a bit far if you have a single monitor. 

I found a couple of command line to move the windows.

```
$ xwininfo -tree -root | grep  'minarca'
   0x54003bf "Minarca Backup": ("minarca" "Minarca")  900x560+10+45  +0+397
$ xdotool windowactivate 0x54003bf
XGetWindowProperty[_NET_WM_DESKTOP] failed (code=1)
$ xdotool windowmove 0x54003bf 100 100
```

**Comment by ikus060** [comment]
> yes, the window showed up.

Great !

> But what causes this behavior?

It's a miss calculation of the window coordinate. Not sure exactly what is the culprit because we delegate this calculation to the widget toolkit. Do you have a particular setup that might interfere with the display. e.g.: Dual monitor, HiRes monitor, scaling, fractional scaling, etc.

**Comment by ikus060** [comment]
A screenshot of your display settings might help alot. e.g.:

![image](https://github.com/ikus060/minarca/assets/921251/84db4668-a248-4c21-9172-c461915881de)

**Comment by ikus060** [comment]
I did not manage to reproduce the problem, by enabling scaling or fractional scaling.

**Comment by ikus060** [comment]
@satkas I will try to investigate with the widget toolkit project. Tkinter in this occurrence.

But I'm afraid that without a reliable way to reproduce the problem it won't be possible to get it fixed.

**Comment by satkas** [comment]
This is how my laptop connects to the docking station 


      Creative
        Pebble     Ethernet
            |            |
            |            |
    Docking  Station ------------- HDMI---------------- Second Monitor ------------ another computer
                 |
                 |
                 |
                 |
      laptop (minarca client)
      connected to dock via usb-c.

**Comment by ikus060** [comment]
If you still experience the issue with 4.5.4, could you try with this dev version: https://nexus.ikus-soft.com/repository/apt-dev-bookworm/pool%2Fm%2Fminarca-client%2Fminarca-client_4.5.5.dev1%2Bg4274637_amd64.deb

I remove the code that center the window.

**Comment by ikus060** [comment]
@satkas Did you get the chance to test the development version I provided ? I will integrate the change in the next release if it work for you.

**Comment by satkas** [comment]
I'm sorry for the lack of response. I'm on vacation and I have a docking station at work (the problem occurred on the instance at work). I think I'll be able to test the new version next week. thank you for the information

**Comment by ikus060** [comment]
@satkas Did you manage to test it again ?

**Comment by satkas** [comment]
Hi @ikus060 
Seems good. now the window appears in the upper left corner

**Comment by ikus060** [comment]
@satkas Thanks for testing. I will merge this change soon.
