### ISSUE TITLE
SSH problem

### ISSUE THREAD

**Issue by GrupaEuro** [ikus060/minarca#17]
Hi,
I have problem when try connet windows agent to server.
![image](https://github.com/ikus060/minarca/assets/139246803/4d32a98c-1190-4fcf-bb2a-dcc909ab78b9)

This server is new and cannot connect any computers

**Comment by ikus060** [comment]
@GrupaEuro 

Since you closed the ticket, I guess you found the culprit. Could you share your finding. It might help other if I provide a better error message.
