### ISSUE TITLE
csr issues - access via https not possible

### ISSUE THREAD

**Issue by einzelfabrik** [ikus060/minarca#18]
Hello,
I have installed the server component on my Debain server (_Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-87-generic x86_64_). I have a PLESK administration active here.
I have also created a subdomain: **backup.example.com** and activated the following rule in the additional APACHE/NGINX settings:
 ```
location / {
	proxy_pass http://127.0.0.1:8080/;
}
```
The matching SSL certificate is bound to **backup.example.com** and is active. When I now call **backup.example.com** I see the login of MINARCA - but I get errors in the console: 

`The loading of the image 'http://127.0.0.1:8080/favicon.ico?v=1700610617' was denied because it violates the following Content Security Policy directive: "img-src 'self' data:".`
 and:
`login/:1 The loading of the script 'http://127.0.0.1:8080/static/js/bootstrap.bundle.min.js' was rejected because it violates the following content security policy: "script-src 'self' 'unsafe-inline'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is `

Who can help me?

**Comment by ikus060** [comment]
Hello @einzelfabrik 

I'm really sorry you experience issue using Minarca behind a reverse SSL proxy.

Minarca documenation to configure it behind a reverse proxy is missing. Rdiffweb documentation is more complete on this subject: https://nexus.ikus-soft.com/repository/archive/rdiffweb/2.8.5/doc/networking.html#configure-rdiffweb-behind-nginx-reverse-proxy

Mainly, you need to let Minarca's know it's running behind a proxy as follow:

```
location / {
            # Define proxy header for cherrypy logging.
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $server_name;
            proxy_set_header X-Forwarded-Proto $scheme;
            # Proxy
            proxy_pass http://127.0.0.1:8080/;
    }
```

**Comment by ikus060** [comment]
Ho and you should configure `external-url` if you plan to use email notification:

https://nexus.ikus-soft.com/repository/archive/minarca/5.0.0/doc/configuration.html#configure-external-url

**Comment by einzelfabrik** [comment]
Thank you very much, that works great!
What is still missing in the instructions - you have to deactivate the "proxy mode" - this setting can be found in plesk in the same place as you define the proxy rule.

**Comment by ikus060** [comment]
I'm glad it fixes your issue.

I took note to complete the documentation.
