### ISSUE TITLE
Translation German?

### ISSUE THREAD

**Issue by einzelfabrik** [ikus060/minarca#19]
Hello, is it desired that I create a German translation? I would like to translate the interface and all strings. And would share the results here.

**Comment by ikus060** [comment]
Hello @einzelfabrik 

Translation file are always welcome. There are 3 project to be translated. IF you want, I could provide the "po" file to you. Then you could use something like poedit to provide the translation.

**Comment by einzelfabrik** [comment]
With pleasure! You are welcome to add 👍

**Comment by ikus060** [comment]
Here they are. One file for the server side. The other one for the desktop application.

Thanks a lot for your involvement ! It's mush appreciated.

[messages-desktop.zip](https://github.com/ikus060/minarca/files/13440385/messages-desktop.zip)

[messages-server.zip](https://github.com/ikus060/minarca/files/13440394/messages-server.zip)

**Comment by einzelfabrik** [comment]
Thank you, the po files are not public? When I have translated everything I will send them back to you? Or how do we stay then? Can I compile the client myself? I would celebrate a German version 😉

**Comment by einzelfabrik** [comment]
Thank you - I will translate the file. Can you give me a tip on how to adapt an existing installation (en) to (de)? Server and client.

**Comment by ikus060** [comment]
For the client, you may place the file in `/opt/minarca/minarca_client/locales/`.

For the server you may place the file in `/opt/minarca-server/lib/python3.11/site-packages/rdiffweb/locales`.

But you may also wait for me to add the files to the source code and trigger a new release with you changes.

**Comment by ikus060** [comment]
This should soon be release in 5.0.1:

https://gitlab.com/ikus-soft/minarca/-/pipelines/1084544430
