### ISSUE TITLE
Uninstall Windows Client?

### ISSUE THREAD

**Issue by hg2s** [ikus060/minarca#20]
I am in the process of testing a new v.5.0.1 server with a variety of clients and noticed that the Windows Uninstaller does not completely remove the previous settings from the system. What is the procedure for removing the Windows client so that upon re-installation the client launches with no previous data loaded? -Thank you

**Comment by ikus060** [comment]
Hello @hg2s 

First, I want to wish you an happy new year !

> does not completely remove the previous settings from the system

Indeed, the configuration are left on the system  for the next or previous version. If you want to completly reset the configuration, you can remove the content of `C:\Users\your-user-name\AppData\Local\minarca`.

Don't hesitate to re-open this issue  if needed.
