### ISSUE TITLE
Portainer install help

### ISSUE THREAD

**Issue by PompJoggie** [ikus060/minarca#22]
So I went to Portainer and created a custom template but cannot get it installed. 
Note I want to use port 8081 or another custom port because 8080 is in use already 

https://hub.docker.com/r/ikus060/minarca-server

version: '3.8'

services:
  minarca-server:
    image: ikus060/minarca-server
    ports:
      - "8081:8080"
      - "2222:22"
    volumes:
      # Location of the backups
      - ./backups:/backups
      # Configuration file and local database
      - ./conf:/etc/minarca
      # Application logs
      - ./logs:/var/log/minarca
    restart: always
    environment:
      # Define the URL to be used by users to connect to this container port 8080 running the webserver.
      # This is optional and only required if a reverse proxy is used.
      MINARCA_EXTERNAL_URL: https://minarca.mycompany.com
      # Define the hostname and IP address to be used by Minarca Agent to connect to this container on port 2222 running SSH Server.
      # This is optional and only required if the port used for SSH is not 22.
      MINARCA_MINARCA_REMOTE_HOST: minarca.mycompany.com:2222

Looks like it does not like the version for some reason and the cannot find the image on Dockerhub? 
Error | Deployment error | 
Failed to deploy a stack: time="2024-10-03T18:25:26Z" level=warning msg="/data/compose/1/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion" minarca-server Pulling minarca-server Error manifest for ikus060/minarca-server:latest not found: manifest unknown: manifest unknown Error response from daemon: manifest for ikus060/minarca-server:latest not found: manifest unknown: manifest unknown

**Comment by ikus060** [comment]
Hello @PompJoggie 

You are too early for the party ! Docker deployment is a work in progress and as you see is not working yet. Their are a couple of issues.

To answer your specific question:

> Looks like it does not like the version for some reason and the cannot find the image on Dockerhub?

You are missing a version tag. `docker pull ikus060/minarca-server:6.0.0b9.dev14-g327cbdc-debian12` is working.

**Comment by PompJoggie** [comment]
But i like to party! :-)

Thanks. I go it to work, but now the windows client is not available for download

**Comment by ikus060** [comment]
Thanks for pointing that out. This is a broken link.

The right link to download Minarca is available on the download page: https://minarca.org/download

https://www.ikus-soft.com/archive/minarca/minarca-latest-install.exe

But honestly, you might run into problem if you plan on using the development build of Minarca with docker. It' currently in development and testing. Use at your own risk.

**Comment by PompJoggie** [comment]
Thanks
This link downloaded the client
https://www.ikus-soft.com/archive/minarca/minarca-latest-install.exe
This link gives a 404
https://minarca.org/download

Constructive feedback. 
When you install the windows app you should have an option to create shortcut on the desktop. I had to go hunt for it in Program files but the normal user will not do that. You should also have the option to launch once installed. :-)
